version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: furniture-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: furniture
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/db:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: furniture-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/docker-entrypoint-initdb.d:ro
      - mongo-data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: furniture-es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  postgres-data:
  mongo-data:
  es-data:

